#!/bin/sh

case "$1" in
    start)
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        /usr/bin/module_load hello
        ;;
    stop)
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
        /usr/bin/module_unload hello
        ;;
    *) echo "Usage: "$1" {start|stop}"
esac

exit 0
