#!/bin/sh
set -e
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
    start)
        /usr/bin/aesdchar_load
        ;;
    stop)
        /usr/bin/aesdchar_unload
        ;;
    *) echo "Usage: "$1" {start|stop}"
esac

exit 0
