#!/bin/sh

case "$1" in
    start)
        /usr/bin/module_load faulty
        /usr/bin/module_load hello;;
    stop)
        /usr/bin/module_unload faulty
        /usr/bin/module_unload hello;;
    *) echo "Usage: "$1" {start|stop}"
esac

exit 0
